version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "6432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "cookr"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: m.staykov06@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  db_data:

networks:
      default:
        name: network
